# Generated by Django 4.1.7 on 2023-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_elektronika_pishiriqlar_sigaret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pishiriqlar',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
